# Generated by Django 5.2.4 on 2025-07-18 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0002_alter_personne_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='age',
        ),
        migrations.AddField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
