# Generated by Django 5.2.4 on 2025-07-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0003_remove_personne_age_personne_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
