# Generated by Django 5.2.4 on 2025-07-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0004_alter_personne_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='code_produit',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
