# Generated by Django 5.2.4 on 2025-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0005_alter_produit_code_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='forme',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injectable', 'Injectable'), ('pommade', 'Pommade'), ('creme', 'Crème'), ('suppositoire', 'Suppositoire'), ('collyre', 'Collyre'), ('suspension', 'Suspension'), ('poudre', 'Poudre'), ('autre', 'Autre')], max_length=50),
        ),
    ]
