# Generated by Django 5.2.4 on 2025-07-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0007_produit_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandefond',
            name='code_sortie_fond',
        ),
    ]
