# Generated by Django 5.2.4 on 2025-07-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0008_remove_demandefond_code_sortie_fond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandefond',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='demandefond',
            name='quantite',
        ),
        migrations.AddField(
            model_name='designer',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
