# Generated by Django 4.2.23 on 2025-07-20 18:47

from django.db import migrations, models
from django.db import transaction

# Ajout de la fonction pour remplir numero_demande
def remplir_numero_demande(apps, schema_editor):
    DemandeFond = apps.get_model('CAHMS', 'DemandeFond')
    with transaction.atomic():
        for idx, demande in enumerate(DemandeFond.objects.order_by('id'), start=1):
            demande.numero_demande = f"DM{idx:03d}"
            demande.save(update_fields=['numero_demande'])


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0009_remove_demandefond_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandefond',
            name='numero_demande',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RunPython(
            code=remplir_numero_demande,
            reverse_code=migrations.RunPython.noop
        ),
    ]
