# Generated by Django 4.2.23 on 2025-07-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0010_demandefond_numero_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandefond',
            name='numero_demande',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
