# Generated by Django 5.2.4 on 2025-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0011_alter_demandefond_numero_demande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='contenir',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personne',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
