# Generated by Django 5.2.4 on 2025-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0012_remove_commande_quantite_contenir_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('mcg', 'mcg'), ('mg/ml', 'mg/ml'), ('g/ml', 'g/ml'), ('mg/5ml', 'mg/5ml'), ('g/100ml', 'g/100ml'), ('%', '%'), ('UI/ml', 'UI/ml'), ('µg/ml', 'µg/ml'), ('mg/g', 'mg/g'), ('g_tube', 'g (tube)'), ('UI', 'UI (unités internationales)')], max_length=20),
        ),
    ]
