# Generated by Django 4.2.23 on 2025-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0013_alter_produit_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionner',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
