# Generated by Django 4.2.23 on 2025-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0014_approvisionner_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité en stock'),
        ),
    ]
