# Generated by Django 4.2.23 on 2025-08-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0015_produit_quantite_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
    ]
