# Generated by Django 4.2.23 on 2025-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAHMS', '0016_remove_commande_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaisse',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
